- id: doi:10.1002/adma.201404707
  image: images/publications/001_Adv_Mater_2015.png
  tags:
    - sensor
- id: doi:10.1021/acsnano.5b00786
  image: images/publications/002_ACS_Nano_2015.png
  tags:
    - catalysis
- id: doi:10.1038/ncomms9294
  image: images/publications/003_NC_2015.png
  tags:
    - functional materials
- id: doi:10.1021/acs.inorgchem.5b02874
  image: images/publications/004_Inorg_Chem_2016.png
  tags:
    - functional materials
- id: doi:10.1021/acs.nanolett.6b00870
  image: images/publications/005_Nano_Lett_2016.png
  tags:
    - battery
- id: doi:10.1002/adfm.201602734
  image: images/publications/006_AFM_2016.png
  tags:
    - battery
- id: doi:10.1016/j.nanoen.2016.12.037
  image: images/publications/007_Nano_Energy_2017.png
  tags:
    - battery
- id: doi:10.1021/acs.nanolett.6b04830
  image: images/publications/008_Nano_Lett_2017.png
  tags:
    - battery
- id: doi:10.1016/j.electacta.2017.08.166
  image: images/publications/009_Electrochim_Acta_2017.png
  tags:
    - battery
- id: doi:10.1016/j.jiec.2017.08.035
  image: images/publications/010_JIEC_2018.png
  tags:
    - functional materials
- id: doi:10.1039/C7NR08161H
  image: images/publications/011_Nanoscale_2018.png
  tags:
    - catalysis
- id: doi:10.1002/smll.201802191
  image: images/publications/012_Small_2018.png
  tags:
    - catalysis
- id: doi:10.1038/s41467-018-06147-8
  image: images/publications/013_NC_2018.png
  tags:
    - sensor
- id: doi:10.1021/acscatal.8b01725
  image: images/publications/014_ACS_Catal_2018.png
  tags:
    - catalysis
    - battery
- id: doi:10.1021/acsami.8b13517
  image: images/publications/015_ACS_AMI_2018.png
  tags:
    - sensor
- id: doi:10.1039/C8EE01503A
  image: images/publications/016_EES_2019.png
  tags:
    - battery
- id: doi:10.1021/acscatal.8b03446
  image: images/publications/017_ACS_Catal_2019.png
  tags:
    - catalysis
- id: doi:10.1002/adfm.201806937
  image: images/publications/018_AFM_2019.png
  tags:
    - battery
- id: doi:10.1038/s41467-019-09339-y
  image: images/publications/019_NC_2019.png
  tags:
    - catalysis
- id: doi:10.1021/jacs.9b00543
  image: images/publications/020_JACS_2019.png
  tags:
    - battery
- id: doi:10.1002/adfm.201901217
  image: images/publications/021_AFM_2019.png
  tags:
    - catalysis
- id: doi:10.1021/acsami.9b04653
  image: images/publications/022_ACS_AMI_2019.png
  tags:
    - sensor
- id: doi:10.1021/acs.nanolett.9b01334
  image: images/publications/023_Nano_Lett_2019.png
  tags:
    - battery
- id: doi:10.1021/acsnano.9b03525
  image: images/publications/024_ACS_Nano_2019.png
  tags:
    - catalysis
    - battery
- id: doi:10.1021/acs.chemmater.9b02346
  image: images/publications/025_CM_2019.png
  tags:
    - functional materials
- id: doi:10.1021/acscatal.9b02700
  image: images/publications/026_ACS_Catal_2020.png
  tags:
    - catalysis
- id: doi:10.1038/s41467-019-14272-1
  image: images/publications/027_NC_2020.png
- id: doi:10.1002/aenm.202000563
  image: images/publications/028_AEM_2020.png
- id: doi:10.1002/advs.202000788
  image: images/publications/029_Adv_Sci_2020.png
- id: doi:10.1039/D0SC02785E
  image: images/publications/030_Chem_Sci_2020.png
- id: doi:10.3389/fenrg.2021.606313
  image: images/publications/031_FER_2021.png
- id: doi:10.1016/j.jpowsour.2021.229633
  image: images/publications/032_JPS_2021.png
- id: doi:10.1039/D1TC01333E
  image: images/publications/033_JMCC_2021.png
- id: doi:10.1002/aenm.202102096
  image: images/publications/034_AEM_2021.png
- id: doi:10.1021/acs.chemmater.2c01046
  image: images/publications/035_CM_2022.png
- id: doi:10.1021/acsami.2c07400
  image: images/publications/036_ACS_AMI_2022.png
- id: doi:10.1021/acs.jpcc.2c07099
  image: images/publications/037_JPCC_2023.png
- id: doi:10.1038/s41467-023-38964-x
  image: images/publications/038_NC_2023.png
- id: doi:10.1002/adma.202303588
  image: images/publications/039_AM_2023.png
- id: doi:10.1002/adma.202303283
  image: images/publications/040_AM_2023.png
- id: doi:10.1002/adfm.202302543
  image: images/publications/041_AFM_2023.png
- id: doi:10.1002/adma.202311559
  image: images/publications/042_AM_2024.png
- id: doi:10.1126/science.adl2835
  image: images/publications/043_Science_2024.png
- id: doi:10.1002/adfm.202416560
  image: images/publications/044_AFM_2025.png
- id: doi:10.1021/acs.est.4c14332
  image: images/publications/045_EST_2025.png
- id: doi:10.1021/acs.chemmater.5c00977
  image: images/publications/046_CM_2025.png
- id: doi:10.1021/acsnano.5c07992
  image: images/publications/047_ACS Nano_2025.png
- id: doi:10.1021/acs.chemmater.5c02171
  image: images/publications/048_CM_2026.png
- id: doi:10.1016/j.jaerosci.2026.106767
  image: images/publications/049_JAS_2026.png
- id: doi:10.1103/zk45-6lb2
  image: images/publications/050_PRB_2026.png
- id: doi:10.1103/zhk4-flgd
  image: images/publications/051_PRM_2026.png

